### ISSUE TITLE
Ergonomics ideas

### ISSUE THREAD

**Issue by coder543** [mostynb/zstdpool-syncpool#4]
I like that this package exists, and I wish that the upstream zstd library would do something like this itself.

From the README here:

```go
// Create a sync.Pool which returns wrapped *zstd.Decoder's.
decoderPool := syncpool.NewDecoderPool(zstd.WithDecoderConcurrency(1))

// Get a DecoderWrapper and use it.
decoder := decoderPool.Get().(*syncpool.DecoderWrapper) 
decoder.Reset(compressedDataReader)
_, err = io.Copy(uncompressedDataWriter, decoder)
````

Since there are separate functions for `NewDecoderPool` and `NewEncoderPool`, it seems like there could be some thin wrapper types around `*sync.Pool`, such that `.Get()` would automatically return a `*syncpool.DecoderWrapper` or `*syncpool.EncoderWrapper`, instead of requiring the caller to perform that type assertion.

Similarly, if you have to `Reset` after each `Get`... maybe `Get` should just take an `io.Reader` and hand back a fully prepared decoder? Together, these changes would make it really hard for someone to misuse this library.

Just some thoughts, but the current simplicity of this package is definitely nice too.

**Comment by mostynb** [comment]
> ... I wish that the upstream zstd library would do something like this itself.

Same here. I think @klauspost would like that too.

How does #5 look?

**Comment by coder543** [comment]
I left one comment, but other than that, it looks like exactly what I wanted. It looks great!

**Comment by mostynb** [comment]
Merged, updated the version of github.com/klauspost/compress and made a v0.0.11 release. Thanks for the suggestion!
